# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Like.create([
  { :user_id => 7, :user_who_is_liked => 6, :created_at => "2013-06-21 16:41:15", :updated_at => "2013-06-21 16:41:15" },
  { :user_id => 7, :user_who_is_liked => 5, :created_at => "2013-06-21 16:41:18", :updated_at => "2013-06-21 16:41:18" },
  { :user_id => 18, :user_who_is_liked => 16, :created_at => "2013-06-22 01:28:51", :updated_at => "2013-06-22 01:28:51" }
], :without_protection => true )



Location.create([
  { :latitude => 37.7141454, :longitude => -122.25, :user_id => 14, :created_at => "2013-06-21 19:06:15", :updated_at => "2013-06-21 19:06:15", :name => "San Francisco Bay Area", :gmaps => true },
  { :latitude => 40.7104012, :longitude => -74.0034008, :user_id => 15, :created_at => "2013-06-21 19:06:58", :updated_at => "2013-06-21 19:06:58", :name => "Greater New York City Area", :gmaps => true },
  { :latitude => 37.7141454, :longitude => -122.25, :user_id => 17, :created_at => "2013-06-21 22:59:54", :updated_at => "2013-06-21 22:59:54", :name => "San Francisco Bay Area", :gmaps => true },
  { :latitude => 37.7141454, :longitude => -122.25, :user_id => 18, :created_at => "2013-06-21 23:15:29", :updated_at => "2013-06-21 23:15:29", :name => "San Francisco Bay Area", :gmaps => true },
  { :latitude => 40.7143528, :longitude => -74.0059731, :user_id => 18, :created_at => "2013-06-22 01:23:49", :updated_at => "2013-06-22 01:23:49", :name => "New York", :gmaps => true },
  { :latitude => 37.7141454, :longitude => -122.25, :user_id => 19, :created_at => "2013-06-22 03:52:24", :updated_at => "2013-06-22 03:52:24", :name => "San Francisco Bay Area", :gmaps => true },
  { :latitude => 48.856614, :longitude => 2.3522219, :user_id => 19, :created_at => "2013-06-22 03:58:49", :updated_at => "2013-06-22 03:58:49", :name => "Paris", :gmaps => true }
], :without_protection => true )



Session.create([
  { :created_at => nil, :updated_at => nil }
], :without_protection => true )



Tag.create([
  { :name => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



User.create([
  { :created_at => "2013-06-21 18:56:50", :updated_at => "2013-06-21 18:56:50", :firstName => "Max", :lastName => "Man", :email => "wahl77test@gmail.com", :picture_url => nil, :headline => nil },
  { :created_at => "2013-06-21 19:06:15", :updated_at => "2013-06-21 19:06:15", :firstName => "Holly", :lastName => "Amanda", :email => "linker.user3@gmail.com", :picture_url => "http://m3.licdn.com/mpr/mprx/0_LPiHRoi7hTfc-0jSbKTBRW87CkEsrJySbNcBReC7gbYEfgwDWv1XvH9Tu2o5POgTXK39qfp1iWIo", :headline => nil },
  { :created_at => "2013-06-21 19:06:58", :updated_at => "2013-06-21 19:06:58", :firstName => "Nick", :lastName => "Lambin", :email => "linker.user4@gmail.com", :picture_url => "http://m3.licdn.com/mpr/mprx/0_W1fpiDbOR0fEAh5qIrp_i7L2MMyIl5vqwqR_imF2QseRm3CNLz0rSaPGBApq-CN4erDG2dMRQ902", :headline => nil },
  { :created_at => "2013-06-21 22:59:53", :updated_at => "2013-06-21 22:59:53", :firstName => "Adam", :lastName => "Daigian", :email => "adam.daigian@gmail.com", :picture_url => "http://m3.licdn.com/mpr/mprx/0_JE55fCYQ3U03WY_kBmLnfhswTMRhwZ_kUHlVf3JVYyfrNpNXvuvWTTSq7cU0HxCe4WbUhQFf-ZW3", :headline => nil },
  { :created_at => "2013-06-21 23:15:28", :updated_at => "2013-06-21 23:15:28", :firstName => "Jeff", :lastName => "Smith", :email => "linker.user1@gmail.com", :picture_url => "http://m3.licdn.com/mpr/mprx/0_z0kCB3PL-iWxDnurBVbjB_8st30ySnDrcOKjBCCsSGIut-VKMJNmJG9NyWx_al2pqpQyZLK-TDhB", :headline => nil },
  { :created_at => "2013-06-22 03:52:23", :updated_at => "2013-06-22 03:52:23", :firstName => "Franky", :lastName => "Wahl", :email => "wahl77+LinkedIn@gmail.com", :picture_url => "http://m3.licdn.com/mpr/mprx/0_fquK8j-YRpzQA6Lq7cSi8YzpMUKQ15kqSzZf8YqaQYkn23PN_-yyaO8hBzrMKC54acmm7JEOsOlQ", :headline => "Web Development Immersive Student at General Assembly" }
], :without_protection => true )


